/*
 * Copyright (c) 2025 OpenCOS.
 */

#include "CosTest.h"

#include <libcos/CosDoc.h>
#include <libcos/CosObjID.h>
#include <libcos/CosParser.h>
#include <libcos/CosTrailer.h>
#include <libcos/common/CosError.h>
#include <libcos/io/CosMemoryStream.h>
#include <libcos/io/CosStream.h>
#include <libcos/objects/CosDictObjNode.h>
#include <libcos/objects/CosIndirectObjNode.h>
#include <libcos/objects/CosObjNode.h>

#include <stdlib.h>

COS_ASSUME_NONNULL_BEGIN

// Parses in-memory PDF bytes (which may contain NULs) and returns the document. The caller owns
// the document and, on success, the returned stream, which must outlive the document.
static CosDoc * COS_Nullable
parse_pdf_bytes_(const unsigned char *bytes,
                 size_t size,
                 CosMemoryStream * COS_Nullable * COS_Nullable out_stream)
{
    CosDoc *doc = cos_doc_create(NULL);
    CosMemoryStream *stream = NULL;
    CosParser *parser = NULL;
    CosError error = cos_error_none();

    if (!doc) {
        goto failure;
    }

    stream = cos_memory_stream_create_readonly(bytes, size);
    if (!stream) {
        goto failure;
    }

    parser = cos_parser_create(doc, (CosStream *)stream);
    if (!parser) {
        goto failure;
    }

    if (!cos_parser_parse(parser, &error)) {
        goto failure;
    }

    if (out_stream) {
        *out_stream = stream;
    }
    return doc;

failure:
    if (doc) {
        cos_doc_destroy(doc);
    }
    if (stream) {
        cos_stream_close((CosStream *)stream);
    }
    return NULL;
}

// A minimal PDF whose cross-reference table is a FlateDecode + PNG-Predictor-12 xref stream.
// Objects: 0 free, 1 in-use catalog @9, 2 in-use (the xref stream @45), 3 compressed (type 2).
// Generated by tests scripts and round-trip verified.
// clang-format off
static const unsigned char xref_stream_pdf[] = {
    0x25, 0x50, 0x44, 0x46, 0x2d, 0x31, 0x2e, 0x35, 0x0a, 0x31, 0x20, 0x30,
    0x20, 0x6f, 0x62, 0x6a, 0x0a, 0x3c, 0x3c, 0x20, 0x2f, 0x54, 0x79, 0x70,
    0x65, 0x20, 0x2f, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x20, 0x3e,
    0x3e, 0x0a, 0x65, 0x6e, 0x64, 0x6f, 0x62, 0x6a, 0x0a, 0x32, 0x20, 0x30,
    0x20, 0x6f, 0x62, 0x6a, 0x0a, 0x3c, 0x3c, 0x20, 0x2f, 0x54, 0x79, 0x70,
    0x65, 0x20, 0x2f, 0x58, 0x52, 0x65, 0x66, 0x20, 0x2f, 0x53, 0x69, 0x7a,
    0x65, 0x20, 0x34, 0x20, 0x2f, 0x57, 0x20, 0x5b, 0x31, 0x20, 0x32, 0x20,
    0x31, 0x5d, 0x20, 0x2f, 0x52, 0x6f, 0x6f, 0x74, 0x20, 0x31, 0x20, 0x30,
    0x20, 0x52, 0x20, 0x2f, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x20, 0x2f,
    0x46, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x20,
    0x2f, 0x44, 0x65, 0x63, 0x6f, 0x64, 0x65, 0x50, 0x61, 0x72, 0x6d, 0x73,
    0x20, 0x3c, 0x3c, 0x20, 0x2f, 0x50, 0x72, 0x65, 0x64, 0x69, 0x63, 0x74,
    0x6f, 0x72, 0x20, 0x31, 0x32, 0x20, 0x2f, 0x43, 0x6f, 0x6c, 0x75, 0x6d,
    0x6e, 0x73, 0x20, 0x34, 0x20, 0x2f, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73,
    0x20, 0x31, 0x20, 0x2f, 0x42, 0x69, 0x74, 0x73, 0x50, 0x65, 0x72, 0x43,
    0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x20, 0x38, 0x20, 0x3e,
    0x3e, 0x20, 0x2f, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x20, 0x32, 0x37,
    0x20, 0x3e, 0x3e, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x0a, 0x78,
    0xda, 0x63, 0x62, 0x60, 0x60, 0xf8, 0xcf, 0xc4, 0xc8, 0xc0, 0xc9, 0xc8,
    0xc4, 0xc0, 0xa0, 0xc2, 0x00, 0x64, 0x5d, 0x61, 0x00, 0x00, 0x13, 0x95,
    0x02, 0x0c, 0x0a, 0x65, 0x6e, 0x64, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d,
    0x0a, 0x65, 0x6e, 0x64, 0x6f, 0x62, 0x6a, 0x0a, 0x73, 0x74, 0x61, 0x72,
    0x74, 0x78, 0x72, 0x65, 0x66, 0x0a, 0x34, 0x35, 0x0a, 0x25, 0x25, 0x45,
    0x4f, 0x46,
};
// clang-format on

static int
parses_trailer_and_root(void)
{
    CosMemoryStream *stream = NULL;
    CosDoc *doc = parse_pdf_bytes_(xref_stream_pdf, sizeof(xref_stream_pdf), &stream);
    TEST_EXPECT(doc != NULL);

    CosTrailer * const trailer = cos_doc_get_trailer(doc);
    TEST_EXPECT(trailer != NULL);
    // A single-revision file has no older trailer.
    TEST_EXPECT(cos_trailer_get_prev(trailer) == NULL);

    // The trailer carries /Root, and the document resolved the root reference.
    CosObjNode *root_entry = NULL;
    TEST_EXPECT(cos_dict_obj_node_get_value_with_string(cos_trailer_get_dict(trailer),
                                                        "Root",
                                                        &root_entry,
                                                        NULL));
    TEST_EXPECT(root_entry != NULL);
    TEST_EXPECT(cos_doc_get_root(doc) != NULL);

    cos_doc_destroy(doc);
    cos_stream_close((CosStream *)stream);
    return EXIT_SUCCESS;
}

static int
resolves_in_use_object(void)
{
    CosMemoryStream *stream = NULL;
    CosDoc *doc = parse_pdf_bytes_(xref_stream_pdf, sizeof(xref_stream_pdf), &stream);
    TEST_EXPECT(doc != NULL);

    // Object 1 is a type-1 (in-use) entry pointing at the catalog dictionary.
    CosError error = cos_error_none();
    CosIndirectObjNode *indirect = cos_doc_get_object(doc, cos_obj_id_make(1, 0), &error);
    TEST_EXPECT(indirect != NULL);
    TEST_EXPECT(error.code == COS_ERROR_NONE);

    CosObjNode *value = cos_indirect_obj_node_get_value(indirect);
    TEST_EXPECT(value != NULL);
    TEST_EXPECT(cos_obj_node_get_type(value) == CosObjNodeType_Dict);

    cos_obj_node_release((CosObjNode *)indirect);
    cos_doc_destroy(doc);
    cos_stream_close((CosStream *)stream);
    return EXIT_SUCCESS;
}

static int
free_entry_returns_error(void)
{
    CosMemoryStream *stream = NULL;
    CosDoc *doc = parse_pdf_bytes_(xref_stream_pdf, sizeof(xref_stream_pdf), &stream);
    TEST_EXPECT(doc != NULL);

    // Object 0 is a type-0 (free) entry.
    CosError error = cos_error_none();
    CosObjNode *obj = cos_doc_get_object(doc, cos_obj_id_make(0, 65535), &error);
    TEST_EXPECT(obj == NULL);
    TEST_EXPECT(error.code == COS_ERROR_XREF);

    cos_doc_destroy(doc);
    cos_stream_close((CosStream *)stream);
    return EXIT_SUCCESS;
}

static int
compressed_entry_is_populated(void)
{
    CosMemoryStream *stream = NULL;
    CosDoc *doc = parse_pdf_bytes_(xref_stream_pdf, sizeof(xref_stream_pdf), &stream);
    TEST_EXPECT(doc != NULL);

    // Object 3 is a type-2 (compressed) entry: it must be recognized (proving the xref stream
    // parsed the type field), and retrieval is not yet implemented.
    CosError error = cos_error_none();
    CosObjNode *obj = cos_doc_get_object(doc, cos_obj_id_make(3, 0), &error);
    TEST_EXPECT(obj == NULL);
    TEST_EXPECT(error.code == COS_ERROR_NOT_IMPLEMENTED);

    cos_doc_destroy(doc);
    cos_stream_close((CosStream *)stream);
    return EXIT_SUCCESS;
}

COS_ASSUME_NONNULL_END

TEST_MAIN()
{
    TEST_EXPECT(parses_trailer_and_root() == EXIT_SUCCESS);
    TEST_EXPECT(resolves_in_use_object() == EXIT_SUCCESS);
    TEST_EXPECT(free_entry_returns_error() == EXIT_SUCCESS);
    TEST_EXPECT(compressed_entry_is_populated() == EXIT_SUCCESS);

    return EXIT_SUCCESS;
}
